import React from 'react';
import styled from 'styled-components';
import { ComponentContainer } from './Styled';
import useToggle from '../../../../hooks/useToggle';
import { Button } from './Styled';
import { BsPCircle } from 'react-icons/bs';
function Modal({ handleClick }) {
  return (
    <Overlayy>
      <Contents>
        <Title> TERMS AND CONDITIONS</Title> <br />
        <Content>
          <br />
          <Bold> Privacy Policy </Bold> <br /> Updated at 2023-04-11 <br />
          RGO-Alangilan. ("we," "our," or "us") is committed to protecting your
          privacy. This Privacy Policy explains how your personal information is
          collected, used, and disclosed by RGO-Alangilan. This Privacy Policy
          applies to our website, www.batstateu-tenants.com, and its associated
          subdomains (collectively, our "Service"). By accessing or using our
          Service, you signify that you have read, understood, and agree to our
          collection, storage, use, and disclosure of your personal information
          as described in this Privacy Policy and our Terms of Service.
        </Content>
        <Content>
          <br /> <Bold>Definitions and key terms</Bold> <br />
          For this Privacy Policy:
          <br />
          • Cookie: small amount of data generated by a website and saved by
          your web browser. It is used to identify your browser, provide
          analytics, remember information about you such as your language
          preference or login information.
          <br />• Company: when this policy mentions "Company," "we," "us," or
          "our," it refers to RGO-Alangilan that is responsible for your
          information under this Privacy Policy.
          <br />• Country: where RGO-Alangilan or the owners/founders of
          RGO-Alangilan are based, in this case is Philippines.
          <br />• Customer: refers to the company, organization or person that
          signs up to use the RGO-Alangilan Service to manage the relationships
          with your consumers or service users.
          <br />• Device: any internet connected device such as a phone, tablet,
          computer or any other device that can be used to visit RGO-Alangilan
          and use the services.
          <br />• IP address: Every device connected to the Internet is assigned
          a number known as an Internet protocol (IP) address. These numbers are
          usually assigned in geographic blocks. An IP address can often be used
          to identify the location from which a device is connecting to the
          Internet.
          <br />• Personnel: refers to those individuals who are employed by
          RGO-Alangilan or are under contract to perform a service on behalf of
          one of the parties.
          <br />• Personal Data: any information that directly, indirectly, or
          in connection with other information — including a personal
          identification number - allows for the identification or
          identifiability of a natural person.
          <br />• Service: refers to the service provided by RGO-Alangilan as
          described in the relative terms (if available) and on this platform.
          <br />• Third-party service: refers to advertisers, contest sponsors,
          promotional and marketing partners, and others who provide our content
          or whose products or services we think may interest you.
          <br />• Website: RGO-Alangilan's site, which can be accessed via this
          URL: www.batstateu-tenants.com.
          <br />• You: a person or entity that is registered with RGO-Alangilan
          to use the Services.
        </Content>
        <Content>
          <br /> <Bold> What Information Do We Collect?</Bold> <br />
          We collect information from you when you visit our service, register,
          place an order, subscribe to our newsletter, respond to a survey or
          fill out a form.
          <br />
          •Name / Username
          <br />
          •Phone Numbers
          <br />
          •Email Addresses
          <br />
          •Age
          <br />
          •Password
        </Content>
        <Content>
          <br /> <Bold>How Do We Use The Information We Collect? </Bold>
          <br />
          Any of the information we collect from you may be used in one of the
          following ways:
          <br />
          •To personalize your experience (your information helps us to better
          respond to your individual needs)
          <br />
          •To improve our service (we continually strive to improve our service
          offerings based on the information and feedback we receive from you)
          <br />
          •To improve customer service (your information helps us to more
          effectively respond to your customer service requests and support
          needs)
          <br />
          •To process transactions
          <br />
          •To administer a contest, promotion, survey or other site feature
          <br />
          •To send periodic emails
        </Content>
        <Content>
          <br />{' '}
          <Bold> When do we use customer information from third parties?</Bold>{' '}
          <br />
          We receive some information from the third parties when you contact
          us. For example, when you submit your email address to us to show
          interest in becoming our customer, we receive information from a third
          party that provides automated fraud detection services to us. We also
          occasionally collect information that is made publicly available on
          social media websites. You can control how much of your information
          social media websites make public by visiting these websites and
          changing your privacy settings.
        </Content>
        <Content>
          <br />{' '}
          <Bold>
            Do we share the information we collect with third parties?
          </Bold>
          <br />
          We may share the information that we collect, both personal and
          non-personal, with third parties such as advertisers, contest
          sponsors, promotional and marketing partners, and others who provide
          our content or whose products or services we think may interest you.
          We may also share it with our current and future affiliated companies
          and business partners, and if we are involved in a merger, asset sale
          or other business reorganization, we may also share or transfer your
          personal and non-personal information to our successors-in-interest
        </Content>
        <Content>
          We may engage trusted third party service providers to perform
          functions and provide services to us, such as hosting and maintaining
          our servers and our service, database storage and management, e-mail
          management, storage marketing, credit card processing, customer
          service and fulfilling orders for products and services you may
          purchase through our platform. We will likely share your personal
          information, and possibly some non-personal information, with these
          third parties to enable them to perform these services for us and for
          you We may share portions of our log file data, including IP
          addresses, for analytics purposes with third parties such as web
          analytics partners, application developers, and ad networks. If your
          IP address is shared, it may be used to estimate general location and
          other technographics such as connection speed, whether you have
          visited the service in a shared location, and type of device used to
          visit the service. They may aggregate information about our
          advertising and what you see on the service and then provide auditing.
          research and reporting for us and our advertisers. We may also
          disclose personal and non-personal information about you to government
          or law enforcement officials or private parties as we, in our sole
          discretion, believe necessary or appropriate in order to respond to
          claims, legal process (including subpoenas), to protect our rights and
          interests or those of a third party, the safety of the public or any
          person, to prevent or stop any illegal, unethical, or legally
          actionable activity, or to otherwise comply with applicable court
          orders, laws, rules and regulations.
        </Content>
        <Content>
          {' '}
          <br />
          <Bold>
            {' '}
            Where and when is information collected from customers and end
            users?
          </Bold>{' '}
          <br />
          We will collect personal information that you submit to us. We may
          also receive personal information about you from third parties as
          described above.
        </Content>
        <Buttons onClick={handleClick}>Back</Buttons>
      </Contents>
    </Overlayy>
  );
}

export default Modal;
const Con = styled.div`
  display: flex;
  gap: 10px;
  align-items: center;
  flex-direction: column;
  justify-content: space-between;
  padding: 20px;
  height: 90%;
  width: 100%;

  border: 1px solid;
  color: black;
  border-radius: 10px;
  background-color: white;
  overflow-y: auto;
  overflow-x: hidden;
  box-shadow: rgb(38, 57, 77) 0px 20px 30px -10px;
`;
const Content = styled.div`
  @media screen and (max-width: 767px) {
    font-size: 12px;
    width: 95%;
  }

  padding: 2px;
  font-size: 14px;
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
`;

const Buttons = styled(Button)`
  font-size: 12px;
  width: 40%;
`;
const Title = styled.div`
  color: #c52d2d;
  font-weight: bold;
  text-align: center;
`;
const Bold = styled.p`
  @media screen and (max-width: 767px) {
    font-size: 12px;
  }
  display: inline;
  font-weight: bold;
  font-size: 15px;
  text-align: center;
`;

// overlay: {

// },
// content: {

// },
const Overlayy = styled.div`
  width: 100%;
  height: 100%;
  z-index: 10;
`;

const Contents = styled.div`
  border-radius: 10px;
  width: 850px;
  height: 700px;
  overflow-y: scroll;
  overflow-x: hidden;
  padding: 20px;
  background-color: white;
  // Centering the modal
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
`;
