import React from 'react';
import styled from 'styled-components';
import { ComponentContainer } from './Styled';
import useToggle from '../../../../hooks/useToggle';
import { Button } from './Styled';
import { BsPCircle } from 'react-icons/bs';
function Modal({ handleClick }) {
  return (
    <Overlayy>
      <Contents>
        <Title> TERMS AND CONDITIONS</Title>
        <br />
        <Bold> Privacy Policy </Bold> <br /> Updated at 2023-04-11 <br />
        <br />
        <Content>
          RGO-Alangilan. ("we," "our," or "us") is committed to protecting your
          privacy. This Privacy Policy explains how your personal information is
          collected, used, and disclosed by RGO-Alangilan. This Privacy Policy
          applies to our website, www.batstateu-tenants.com, and its associated
          subdomains (collectively, our "Service"). By accessing or using our
          Service, you signify that you have read, understood, and agree to our
          collection, storage, use, and disclosure of your personal information
          as described in this Privacy Policy and our Terms of Service.
        </Content>
        <br /> <Bold>Definitions and key terms</Bold> <br /> For this Privacy
        Policy:
        <Content>
          <br />
          • Cookie: small amount of data generated by a website and saved by
          your web browser. It is used to identify your browser, provide
          analytics, remember information about you such as your language
          preference or login information.
          <br />• Company: when this policy mentions "Company," "we," "us," or
          "our," it refers to RGO-Alangilan that is responsible for your
          information under this Privacy Policy.
          <br />• Country: where RGO-Alangilan or the owners/founders of
          RGO-Alangilan are based, in this case is Philippines.
          <br />• Customer: refers to the company, organization or person that
          signs up to use the RGO-Alangilan Service to manage the relationships
          with your consumers or service users.
          <br />• Device: any internet connected device such as a phone, tablet,
          computer or any other device that can be used to visit RGO-Alangilan
          and use the services.
          <br />• IP address: Every device connected to the Internet is assigned
          a number known as an Internet protocol (IP) address. These numbers are
          usually assigned in geographic blocks. An IP address can often be used
          to identify the location from which a device is connecting to the
          Internet.
          <br />• Personnel: refers to those individuals who are employed by
          RGO-Alangilan or are under contract to perform a service on behalf of
          one of the parties.
          <br />• Personal Data: any information that directly, indirectly, or
          in connection with other information — including a personal
          identification number - allows for the identification or
          identifiability of a natural person.
          <br />• Service: refers to the service provided by RGO-Alangilan as
          described in the relative terms (if available) and on this platform.
          <br />• Third-party service: refers to advertisers, contest sponsors,
          promotional and marketing partners, and others who provide our content
          or whose products or services we think may interest you.
          <br />• Website: RGO-Alangilan's site, which can be accessed via this
          URL: www.batstateu-tenants.com.
          <br />• You: a person or entity that is registered with RGO-Alangilan
          to use the Services.
        </Content>
        <br /> <Bold> What Information Do We Collect?</Bold> <br />
        <Content>
          We collect information from you when you visit our service, register,
          place an order, subscribe to our newsletter, respond to a survey or
          fill out a form.
          <br />
          •Name / Username
          <br />
          •Phone Numbers
          <br />
          •Email Addresses
          <br />
          •Age
          <br />
          •Password
        </Content>
        <br /> <Bold>How Do We Use The Information We Collect? </Bold>
        <br />
        <Content>
          {' '}
          Any of the information we collect from you may be used in one of the
          following ways:
          <br />
          •To personalize your experience (your information helps us to better
          respond to your individual needs)
          <br />
          •To improve our service (we continually strive to improve our service
          offerings based on the information and feedback we receive from you)
          <br />
          •To improve customer service (your information helps us to more
          effectively respond to your customer service requests and support
          needs)
          <br />
          •To process transactions
          <br />
          •To administer a contest, promotion, survey or other site feature
          <br />
          •To send periodic emails
        </Content>
        <br />{' '}
        <Bold>
          {' '}
          When do we use customer information from third parties?
        </Bold>{' '}
        <br />
        <Content>
          We receive some information from the third parties when you contact
          us. For example, when you submit your email address to us to show
          interest in becoming our customer, we receive information from a third
          party that provides automated fraud detection services to us. We also
          occasionally collect information that is made publicly available on
          social media websites. You can control how much of your information
          social media websites make public by visiting these websites and
          changing your privacy settings.
        </Content>
        <br />{' '}
        <Bold>Do we share the information we collect with third parties?</Bold>
        <br />
        <Content>
          We may share the information that we collect, both personal and
          non-personal, with third parties such as advertisers, contest
          sponsors, promotional and marketing partners, and others who provide
          our content or whose products or services we think may interest you.
          We may also share it with our current and future affiliated companies
          and business partners, and if we are involved in a merger, asset sale
          or other business reorganization, we may also share or transfer your
          personal and non-personal information to our successors-in-interest
        </Content>
        <Content>
          We may engage trusted third party service providers to perform
          functions and provide services to us, such as hosting and maintaining
          our servers and our service, database storage and management, e-mail
          management, storage marketing, credit card processing, customer
          service and fulfilling orders for products and services you may
          purchase through our platform. We will likely share your personal
          information, and possibly some non-personal information, with these
          third parties to enable them to perform these services for us and for
          you We may share portions of our log file data, including IP
          addresses, for analytics purposes with third parties such as web
          analytics partners, application developers, and ad networks. If your
          IP address is shared, it may be used to estimate general location and
          other technographics such as connection speed, whether you have
          visited the service in a shared location, and type of device used to
          visit the service. They may aggregate information about our
          advertising and what you see on the service and then provide auditing.
          research and reporting for us and our advertisers. We may also
          disclose personal and non-personal information about you to government
          or law enforcement officials or private parties as we, in our sole
          discretion, believe necessary or appropriate in order to respond to
          claims, legal process (including subpoenas), to protect our rights and
          interests or those of a third party, the safety of the public or any
          person, to prevent or stop any illegal, unethical, or legally
          actionable activity, or to otherwise comply with applicable court
          orders, laws, rules and regulations.
        </Content>{' '}
        <br />
        <Bold>
          {' '}
          Where and when is information collected from customers and end users?
        </Bold>{' '}
        <br />
        <Content>
          {' '}
          We will collect personal information that you submit to us. We may
          also receive personal information about you from third parties as
          described above.
        </Content>
        <br />
        <Bold>How Do We Use Your Email Address?</Bold>
        <br />
        <Content>
          {' '}
          By submitting your email address on this website, you agree to receive
          emails from us. You can cancel your participation in any of these
          email lists at any time by clicking on the opt-out link or other
          unsubscribe option that is included in the respective email. We only
          send emails to people who have authorized us to contact them, either
          directly, or through a third party. We do not send unsolicited
          commercial emails, because we hate spam as much as you do. By
          submitting your email address, you also agree to allow us to use your
          email address for customer audience targeting on sites like Facebook,
          where we display custom advertising to specific people who have
          opted-in to receive communications from us. Email addresses submitted
          only through the order processing page will be used for the sole
          purpose of sending you information and updates pertaining to your
          order. If, however, you have provided the same email to us through
          another method, we may use it for any of the purposes stated in this
          Policy. Note: If at any time you would like to unsubscribe from
          receiving future emails, we include detailed unsubscribe instructions
          at the bottom of each email.
        </Content>
        <br />
        <Bold>
          Could my information be transferred to other countries?
        </Bold>{' '}
        <br />
        <Content>
          {' '}
          We are incorporated in Philippines. Information collected via our
          website, through direct interactions with you, or from use of our help
          services may be transferred from time to time to our offices or
          personnel, or to third parties, located throughout the world, and may
          be viewed and hosted anywhere in the world, including countries that
          may not have laws of general applicability regulating the use and
          transfer of such data. To the fullest extent allowed by applicable
          law, by using any of the above, you voluntarily consent to the trans-
          border transfer and hosting of such information.
        </Content>
        <br />
        <Bold>
          Is the information collected through our service secure?
        </Bold>{' '}
        <br />
        <Content>
          {' '}
          We take precautions to protect the security of your information. We
          have physical, electronic, and managerial procedures to help
          safeguard, prevent unauthorized access, maintain data security, and
          correctly use your information. However, neither people nor security
          systems are foolproof, including encryption systems. In addition,
          people can commit intentional crimes, make mistakes or fail to follow
          policies. Therefore, while we use reasonable efforts to protect your
          personal information, we cannot guarantee its absolute security. If
          applicable law imposes any non-disclaimable duty to protect your
          personal information, you agree that intentional misconduct will be
          the standards used to measure our compliance with that duty.
        </Content>
        <br />
        <Bold>Can I update or correct my information?</Bold>
        <br />
        <Content>
          {' '}
          The rights you have to request updates or corrections to the
          information we collect depend on your relationship with us. Personnel
          may update or correct their information as detailed in our internal
          company employment policies. Customers have the right to request the
          restriction of certain uses and disclosures of personally identifiable
          information as follows. You can contact us in order to (1) update or
          correct your personally identifiable information, (2) change your
          preferences with respect to communications and other information you
          receive from us, or (3) delete the personally identifiable information
          maintained about you on our systems (subject to the following
          paragraph), by cancelling your account. Such updates, corrections,
          changes and deletions will have no effect on other information that we
          maintain, or information that we have provided to third parties in
          accordance with this Privacy Policy prior to such update, correction,
          change or deletion. To protect your privacy and security, we may take
          reasonable steps (such as requesting a unique password) to verify your
          identity before granting you profile access or making corrections. You
          are responsible for maintaining the secrecy of your unique password
          and account information at all times. You should be aware that it is
          not technologically possible to remove each and every record of the
          information you have provided to us from our system. The need to back
          up our systems to protect information from inadvertent loss means that
          a copy of your information may exist in a non-erasable form that will
          be difficult or impossible for us to locate. Promptly after receiving
          your request, all personal information stored in databases we actively
          use, and other readily searchable media will be updated, corrected,
          changed or deleted, as appropriate, as soon as and to the extent
          reasonably and technically practicable. If you are an end user and
          wish to update, de <Content></Content>lete, or receive any information
          we have about you, you may do so by contacting the organization of
          which you are a customer.
        </Content>
        <br />
        <Bold> Sale of Business</Bold> <br />
        <Content>
          {' '}
          We reserve the right to transfer information to a third party in the
          event of a sale, merger or other transfer of all or substantially all
          of the assets of us or any of its Corporate Affiliates (as defined
          herein), or that portion of us or any of its Corporate Affiliates to
          which the Service relates, or in the event that we discontinue our
          business or file a petition or have filed against us a petition in
          bankruptcy, reorganization or similar proceeding, provided that the
          third party agrees to adhere to the terms of this Privacy Policy.
        </Content>
        <Bold>
          <br />
          Affiliates
          <br />
        </Bold>
        <Content>
          {' '}
          We may disclose information (including personal information) about you
          to our Corporate Affiliates. For purposes of this Privacy Policy,
          "Corporate Affiliate" means any person or entity which directly or
          indirectly controls, is controlled by or is under common control with
          us, whether by ownership or otherwise. Any information relating to you
          that we provide to our Corporate Affiliates will be treated by those
          Corporate Affiliates in accordance with the terms of this Privacy
          Policy.
        </Content>
        <br /> <Bold>How Long Do We Keep Your Information?</Bold>
        <br />
        <Content>
          {' '}
          We keep your information only so long as we need it to provide service
          to you and fulfill the purposes described in this policy. This is also
          the case for anyone that we share your information with and who
          carries out services on our behalf. When we no longer need to use your
          information and there is no need for us to keep it to comply with our
          legal or regulatory obligations, we'll either remove it from our
          systems or depersonalize it so that we can't identify you.
        </Content>
        <br /> <Bold> How Do We Protect Your Information? </Bold>
        <br />
        <Content>
          {' '}
          We implement a variety of security measures to maintain the safety of
          your personal information when you place an order or enter, submit, or
          access your personal information. We offer the use of a secure server.
          All supplied sensitive/credit information is transmitted via Secure
          Socket Layer (SSL) technology and then encrypted into our Payment
          gateway providers database only to be accessible by those authorized
          with special access rights to such systems, and are required to keep
          the information confidential. After a transaction, your private
          information (credit cards, social security numbers, financials, etc.)
          is never kept on file. We cannot, however, ensure or warrant the
          absolute security of any information you transmit to us or guarantee
          that your information on the Service may not be accessed, disclosed,
          altered, or destroyed by a breach of any of our physical, technical,
          or managerial safeguards.
        </Content>
        <br />
        <Bold>Governing Law</Bold>
        <br />
        <Content>
          The laws of Philippines, excluding its conflicts of law rules, shall
          govern this Agreement and your use of our service. Your use of our
          service may also be subject to other local, state, national, or
          international laws.
        </Content>
        <br />
        <Bold>Your Consent</Bold>
        <br />
        <Content>
          {' '}
          By using our service, registering an account, or making a purchase,
          you consent to this Privacy Policy.
        </Content>
        <br />
        <Bold>Links to Other Websites</Bold>
        <br />
        <Content>
          {' '}
          This Privacy Policy applies only to the Services. The Services may
          contain links to other websites not operated or controlled by. We are
          not responsible for the content, accuracy or opinions expressed in
          such websites, and such websites are not investigated, monitored or
          checked for accuracy or completeness by us. Please remember that when
          you use a link to go from the Services to another website, our Privacy
          Policy is no longer in effect. Your browsing and interaction on any
          other website, including those that have a link on our platform, is
          subject to that website's own rules and policies. Such third parties
          may use their own cookies or other methods to collect information
          about you.
        </Content>
        <br />
        <Bold>Cookies</Bold>
        <br />
        <Content>
          We use "Cookies" to identify the areas of our website that you have
          visited. A Cookie is a small piece of data stored on your computer or
          mobile device by your web browser. We use Cookies to personalize the
          Content that you see on our website. Most web browsers can be set to
          disable the use of Cookies. However, if you disable Cookies, you may
          not be able to access functionality on our website correctly or at
          all. We never place Personally Identifiable Information in Cookies.
        </Content>
        <br /> <Bold>Third-Party Services</Bold>
        <br />
        <Content>
          {' '}
          We may display, include or make available third-party content
          (including data, information, applications and other products
          services) or provide links to third-party websites or services
          ("Third-Party Services"). You acknowledge and agree that we shall not
          be responsible for any Third-Party Services, including their accuracy,
          completeness, timeliness, validity, copyright compliance, legality,
          decency, quality or any other aspect thereof. We do not assume and
          shall not have any liability or responsibility to you or any other
          person or entity for any Third-Party Services.
        </Content>
        <Content>
          Third-Party Services and links thereto are provided solely as a
          convenience to you and you access and use them entirely at your own
          risk and subject to such third parties' terms and conditions.
        </Content>
        <br />
        <Buttons onClick={handleClick} required>
          I ACCEPT ALL THE TERMS AND CONDITIONS
        </Buttons>
      </Contents>
    </Overlayy>
  );
}

export default Modal;
const Con = styled.div`
  display: flex;
  gap: 10px;
  align-items: center;
  flex-direction: column;
  justify-content: space-between;
  padding: 20px;
  height: 90%;
  width: 100%;

  border: 1px solid;
  color: black;
  border-radius: 10px;
  background-color: white;

  overflow-y: auto;
  overflow-x: hidden;
  box-shadow: rgb(38, 57, 77) 0px 20px 30px -10px;
`;
const Content = styled.div`
  @media screen and (max-width: 767px) {
    font-size: 12px;
    width: 95%;
  }
  text-indent: 50px;
  padding: 2px;
  font-size: 14px;
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
`;

const Buttons = styled(Button)`
  font-size: 12px;
  width: auto;
  padding: 10px;
`;
const Title = styled.div`
  color: #c52d2d;
  font-weight: bold;
  text-align: center;
  font-size: 20px;
  border: 1px solid;
  padding: 5px;
  border-radius: 10px; ;
`;
const Bold = styled.p`
  @media screen and (max-width: 767px) {
    font-size: 12px;
  }
  display: inline;
  font-weight: bold;
  font-size: 15px;
  text-align: center;
`;

// overlay: {

// },
// content: {

// },
const Overlayy = styled.div`
  width: 100%;
  height: 100%;
  z-index: 10;
`;

const Contents = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  border-radius: 10px;
  width: 850px;
  height: 700px;
  overflow-y: scroll;
  overflow-x: hidden;
  padding: 20px;
  background-color: white;
  // Centering the modal
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
`;
